### ISSUE TITLE
GCD 的一些知识碎片

### ISSUE THREAD

**Issue by polaris-dxz** [Yggdrasill-7C9/Yggdrasill-7C9.github.io#1]
dispatch_once即使在多线程下执行，也能保证百分百安全。
虽然源代码在大多数情况下也是安全的，但是在多核 CPU 中，正在更新表示是否初始化的标志变量是读取，就有可能多次执行初始化处理。
dispatch_once保证在应用程序只执行一次，适合单例模式。

**Comment by polaris-dxz** [comment]
1个 CPU 核执行的 CPU 命令始终为1

**Comment by polaris-dxz** [comment]
OSX  和 iOS  的核心是  [XNU内核](https://www.jianshu.com/p/362bbf4cb114)

**Comment by polaris-dxz** [comment]
XNU 在发生操作系统时间时，会切换执行路径（汇编层级，例如寄存器的寻址），这被称为**上下文切换。**。

**Comment by polaris-dxz** [comment]
多个线程更新相同资源会造成
* 数据竞争（多个线程更新相同资源）
* 死锁（线程之间相互访问）

当然，使用太多线程会导致大量消耗内存

**Comment by polaris-dxz** [comment]
GCD 的 API
* dispatch queue
  * dispatch queue create
  * main/global dispatch queue
  * dispatch set target queue （变更优先级）
* dispatch after
* dispatch group
* dispatch  barrier async/sync
* dispatch sync/async
* dispatch apply（这东西是循环吗？而且每次运行结果都不一样）
* dispatch suspend/resume
* dispatch semaphore
* dispatch once 
* dispatch io

**Comment by polaris-dxz** [comment]
同步异步执行一个（线程）队列，这个队列可以是串行（Serial）的或者并行（Concurrent）的。

**异步和串行队列可以避免数据竞争**。因为并行队列有可能会同时访问同一个资源啊喂！

**Comment by polaris-dxz** [comment]
因为 dispatch queue 并不像 block 一样具有 OC 对象的处理技术，所以 create 的队列需要手动release。

注：这个队列有 dispatch_retain持有。。。特别说明，ios6之后已经纳入 ARC 管理了，所以也不用管了，非 ARC 还是得释放的，因为 create 的东西不是 get 的

**Comment by polaris-dxz** [comment]
create 的队列你可以给名字置为 NULL，这么做的结果就是调试的时候你就苦逼了，哈哈哈哈哈哈

另外，起名的原则最好遵循 FQDN（逆序全程域名），方便我们调试的时候快速判断是哪个队列

**Comment by polaris-dxz** [comment]
关于 nil 和 NULL 的区别
nil 是类指针
NULL可以给任何指针赋值
[NSNULL null]这是一个对象。。

**Comment by polaris-dxz** [comment]
主队列是一个串行队列，全局队列是并行队列，虽然从字面意思就能判断出来，但是我还是想啰嗦一下

而且主队列和全局队列有一个好处就是，不用手动释放和持有！好赞

**Comment by polaris-dxz** [comment]
* 没研究明白 dispatch_apply的问题

还没研究的：
* dispatch group
* dispatch barrier async/sync
* dispatch semaphore （信号量，抽时间复习下操作系统）

没深研究的
* dispatch suspend/resume(挂起和恢复)

**Comment by Yggdrasill-7C9** [comment]
- [ ]
